# Generated by Django 5.2.4 on 2025-07-06 10:41
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [TrigramExtension()]
